// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"manhhung2111/go-sql/internal/config"
	"manhhung2111/go-sql/internal/engine"
	"manhhung2111/go-sql/internal/grpcserver"
	"manhhung2111/go-sql/internal/parser"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*grpcserver.Server, func(), error) {
	lexer := parser.NewLexer()
	parserParser := parser.NewParser(lexer)
	dataDir := ProvideDataDir(cfg)
	catalog, cleanup, err := ProvideCatalog(dataDir)
	if err != nil {
		return nil, nil, err
	}
	engineEngine := engine.NewEngine(catalog)
	server := grpcserver.NewServer(cfg, parserParser, engineEngine)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(parser.WireSet, grpcserver.WireSet, engine.WireSet, ProvideDataDir,
	ProvideCatalog,
)
