package parser

type TokenType int

const (
	// Special
	EOF TokenType = iota
	ILLEGAL

	// Literals
	IDENT // column names, table names, aliases
	STRING
	NUMBER

	// Reserved words
	SELECT
	FROM
	WHERE
	AND
	OR
	NOT
	INSERT
	INTO
	VALUES
	UPDATE
	SET
	DELETE
	CREATE
	DATABASE
	SHOW
	DATABASES
	DROP
	TABLE
	IF
	EXISTS
	NULL
	DEFAULT
	UNIQUE
	PRIMARY
	KEY
	ALTER
	ADD
	COLUMN
	RENAME
	TO

	// Operators
	EQ
	NEQ
	LT
	LTE
	GT
	GTE

	// Punctuation
	COMMA
	SEMICOLON
	LPAREN
	RPAREN
	ASTERISK

	// Data types
	CHAR
	VARCHAR
	TEXT
	BOOLEAN
	SMALLINT
	MEDIUMINT
	INT
	BIGINT
)

var tokenTypeMapping = map[string]TokenType{
	";": SEMICOLON, ",": COMMA, "(": LPAREN, ")": RPAREN, "*": ASTERISK,
	"=": EQ, "!=": NEQ, "<>": NEQ, "<": LT, "<=": LTE, ">": GT, ">=": GTE,
	"SELECT": SELECT, "FROM": FROM, "WHERE": WHERE, "AND": AND, "OR": OR, "NOT": NOT,
	"INSERT": INSERT, "INTO": INTO, "VALUES": VALUES, "UPDATE": UPDATE, "SET": SET, "DELETE": DELETE,
	"CREATE": CREATE, "DATABASE": DATABASE, "SHOW": SHOW, "DATABASES": DATABASES, "DROP": DROP,
	"TABLE": TABLE, "IF": IF, "EXISTS": EXISTS, "NULL": NULL, "DEFAULT": DEFAULT, "UNIQUE": UNIQUE,
	"PRIMARY": PRIMARY, "KEY": KEY, "CHAR": CHAR, "VARCHAR": VARCHAR, "TEXT": TEXT, "BOOLEAN": BOOLEAN,
	"BOOL": BOOLEAN, "SMALLINT": SMALLINT, "MEDIUMINT": MEDIUMINT, "INT": INT, "BIGINT": BIGINT,
	"ALTER": ALTER, "ADD": ADD, "COLUMN": COLUMN, "RENAME": RENAME, "TO": TO,
}

type Token struct {
	Type     TokenType
	Value    string
	Position int
}
