// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: sql.proto

package sqlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_OK          StatusCode = 0
	StatusCode_PARSE_ERROR StatusCode = 1
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "OK",
		1: "PARSE_ERROR",
	}
	StatusCode_value = map[string]int32{
		"OK":          0,
		"PARSE_ERROR": 1,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sql_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_sql_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_sql_proto_rawDescGZIP(), []int{0}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sql_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=sqlpb.StatusCode" json:"code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // empty when code == OK
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sql_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_OK
}

func (x *QueryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_sql_proto protoreflect.FileDescriptor

const file_sql_proto_rawDesc = "" +
	"\n" +
	"\tsql.proto\x12\x05sqlpb\" \n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"[\n" +
	"\rQueryResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.sqlpb.StatusCodeR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*%\n" +
	"\n" +
	"StatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0f\n" +
	"\vPARSE_ERROR\x10\x012K\n" +
	"\x10SqlParserService\x127\n" +
	"\n" +
	"ParseQuery\x12\x13.sqlpb.QueryRequest\x1a\x14.sqlpb.QueryResponseB!Z\x1fmanhhung2111/go-sql/proto/sqlpbb\x06proto3"

var (
	file_sql_proto_rawDescOnce sync.Once
	file_sql_proto_rawDescData []byte
)

func file_sql_proto_rawDescGZIP() []byte {
	file_sql_proto_rawDescOnce.Do(func() {
		file_sql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sql_proto_rawDesc), len(file_sql_proto_rawDesc)))
	})
	return file_sql_proto_rawDescData
}

var file_sql_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sql_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sql_proto_goTypes = []any{
	(StatusCode)(0),       // 0: sqlpb.StatusCode
	(*QueryRequest)(nil),  // 1: sqlpb.QueryRequest
	(*QueryResponse)(nil), // 2: sqlpb.QueryResponse
}
var file_sql_proto_depIdxs = []int32{
	0, // 0: sqlpb.QueryResponse.code:type_name -> sqlpb.StatusCode
	1, // 1: sqlpb.SqlParserService.ParseQuery:input_type -> sqlpb.QueryRequest
	2, // 2: sqlpb.SqlParserService.ParseQuery:output_type -> sqlpb.QueryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sql_proto_init() }
func file_sql_proto_init() {
	if File_sql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sql_proto_rawDesc), len(file_sql_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sql_proto_goTypes,
		DependencyIndexes: file_sql_proto_depIdxs,
		EnumInfos:         file_sql_proto_enumTypes,
		MessageInfos:      file_sql_proto_msgTypes,
	}.Build()
	File_sql_proto = out.File
	file_sql_proto_goTypes = nil
	file_sql_proto_depIdxs = nil
}
