// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: sql.proto

package sqlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SqlParserService_ParseQuery_FullMethodName = "/sqlpb.SqlParserService/ParseQuery"
)

// SqlParserServiceClient is the client API for SqlParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SqlParserServiceClient interface {
	ParseQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type sqlParserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlParserServiceClient(cc grpc.ClientConnInterface) SqlParserServiceClient {
	return &sqlParserServiceClient{cc}
}

func (c *sqlParserServiceClient) ParseQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, SqlParserService_ParseQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqlParserServiceServer is the server API for SqlParserService service.
// All implementations must embed UnimplementedSqlParserServiceServer
// for forward compatibility.
type SqlParserServiceServer interface {
	ParseQuery(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedSqlParserServiceServer()
}

// UnimplementedSqlParserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlParserServiceServer struct{}

func (UnimplementedSqlParserServiceServer) ParseQuery(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseQuery not implemented")
}
func (UnimplementedSqlParserServiceServer) mustEmbedUnimplementedSqlParserServiceServer() {}
func (UnimplementedSqlParserServiceServer) testEmbeddedByValue()                          {}

// UnsafeSqlParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlParserServiceServer will
// result in compilation errors.
type UnsafeSqlParserServiceServer interface {
	mustEmbedUnimplementedSqlParserServiceServer()
}

func RegisterSqlParserServiceServer(s grpc.ServiceRegistrar, srv SqlParserServiceServer) {
	// If the following call panics, it indicates UnimplementedSqlParserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqlParserService_ServiceDesc, srv)
}

func _SqlParserService_ParseQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlParserServiceServer).ParseQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlParserService_ParseQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlParserServiceServer).ParseQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SqlParserService_ServiceDesc is the grpc.ServiceDesc for SqlParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sqlpb.SqlParserService",
	HandlerType: (*SqlParserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseQuery",
			Handler:    _SqlParserService_ParseQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sql.proto",
}
